### ISSUE TITLE
Alertfy behavior

### ISSUE THREAD

**Issue by AndreLZGava** [mkhairi/alertifyjs-rails#2]
I reallized that new alertyjs don't jump modals to disapear, but in the gem there is this behavior, how can I make it just disapear without jump?

**Comment by mkhairi** [comment]
@AndreLGava, new gem version has been published.

**Comment by AndreLZGava** [comment]
Thank you, tonight i'll test new gem  :D

**Comment by AndreLZGava** [comment]
Hey :)

I update my gem to 1.7.1 but the behavior still is jump on screen, is there an setting to make it just disapear like fade?

**Comment by mkhairi** [comment]
@AndreLGava,
the default transition is pulse. To change other transition, see http://alertifyjs.com/alert/transition.html
