### ISSUE TITLE
Latest release 1.11.2

### ISSUE THREAD

**Issue by NDuggan** [mkhairi/alertifyjs-rails#6]
Commit history shows `v1.11.2` but [Rubygems](https://rubygems.org/gems/alertifyjs-rails) is showing `v1.11.1`.

Can we get a new release for it, please?

**Comment by mkhairi** [comment]
v1.11.2  [published](https://rubygems.org/gems/alertifyjs-rails/versions/1.11.2) 🙇

**Comment by NDuggan** [comment]
Thanks
